version: "3.8"

services:
  db:
    image: postgres:17.6
    container_name: postgres-fastone
    environment:
      POSTGRES_DB: fastone
      POSTGRES_USER: f1
      POSTGRES_PASSWORD: qwer1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: redis-fastone
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "qwer1234"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: