version: "3.8"

services:
  db:
    image: postgres:17.6
    container_name: postgres-fastone
    environment:
      POSTGRES_DB: fastone
      POSTGRES_USER: f1
      POSTGRES_PASSWORD: qwer1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fastone-net

  redis:
    image: redis:7.4-alpine
    container_name: redis-fastone
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--appendonly", "no"]
    networks:
      - fastone-net

networks:
  fastone-net:
    driver: bridge

volumes:
  pgdata:
  redisdata: