server:
  port: 8080

spring:
  profiles:
    active: secret

  application:
    name: FastOne

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fastone}
    username: ${DB_USERNAME:f1}
    password: ${DB_PASSWORD:qwer1234}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:qwer1234}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

#  ai:
#    openai:
#      api-key: ${spring.ai.google.api-key}
#
#    vertex:
#      ai:
#        gemini:
#          project-id: ${spring.ai.vertex.ai.gemini.project-id}
#          location: ${spring.ai.google.location}
#
## JWT 설정
#jwt:
#  secret:
#    key: ${jwt.secret.key}


  ai:
    openai:
      api-key: AIzaSyD-VS6ofTWDj72t2LXUdxxjemITcWviShQ

    vertex:
      ai:
        gemini:
          project-id: 143064894925
          location: us-central1

jwt:
  secret:
    key: yTo4jLx9zYBaTF/Ralw7tiKF6Cw4pCk76+r+YqwUMsA=

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE