server:
  port: 8080

spring:
  application:
    name: FastOne

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fastone}
    username: ${DB_USERNAME:f1}
    password: ${DB_PASSWORD:qwer1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# JWT 설정
jwt:
  secret:
    key: yTo4jLx9zYBaTF/Ralw7tiKF6Cw4pCk76+r+YqwUMsA=

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE