server:
  port: 8080

spring:
  profiles:
    active: secret

  application:
    name: FastOne

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fastone}
    username: ${DB_USERNAME:f1}
    password: ${DB_PASSWORD:qwer1234}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true