server:
  port: 8080

spring:
  profiles:
    active: secret

  application:
    name: FastOne

  data:
    redis:
      host: redis-fastone
      port: 6379

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fastone}
    username: ${DB_USERNAME:f1}
    password: ${DB_PASSWORD:qwer1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  ai:
    openai:
      api-key: ${spring.ai.google.api-key}

    vertex:
      ai:
        gemini:
          project-id: ${spring.ai.vertex.ai.gemini.project-id}
          location: ${spring.ai.google.location}

# JWT 설정
jwt:
  secret:
    key: ${jwt.secret.key}

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE