server:
  port: 8080

spring:
  profiles:
    active: prod

  application:
    name: FastOne

  datasource:
    url: jdbc:postgresql://${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  ai:
    openai:
      api-key: ${CUSTOM_API_KEY}
      chat:
        options:
          model: ${CUSTOM_MODEL}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
